src/resources/__snapshots__/index.test.js.snap
src/resources/offices.js

add 'limit'-filter on offices resource

feature/SKED-3233: feat: add 'limit'-filter on offices resource

---

.travis.yml
package-lock.json
package.json
scripts/release.sh

See JIRA: https://skedify.atlassian.net/browse/SKED-3980

feature/SKED-3980: Update Node from 9.x to 10.x

---

src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/contacts.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-3929

feature/SKED-3929: Add flex availability resources

---

src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/contacts.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4099

feature/SKED-4099: SDK has some incorrect includes defined

---

src/resources/__snapshots__/index.test.js.snap
src/resources/employees.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4215

feature/SKED-4215: Fix web app so that you can log in again

---

.travis.yml
package-lock.json
package.json

> See JIRA: https://skedify.atlassian.net/browse/SKED-4327

feature/SKED-4327: Verify the functionality of the first scope of flex availability v1.1

---

src/Skedify.test.js
src/__snapshots__/Skedify.test.js.snap
src/decorators/withResources/Resource.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4318

feature/SKED-4318: Prep/analysis for integrating new flex availability endpoints in web app

---

src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/officeManagerOffices.js

> See JIRA https://skedify.atlassian.net/browse/SKED-4358

fix(flex-availability): add missing include on office_manager_offices

---

src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/subjects.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4461

feature/SKED-4461: State Management: Fetch availability settings for day/week time slot

---

src/createIdentityProvider/identityProviders/createGrant.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4631

feature/SKED-4631: Timetable VDAB gets regular 401 Unauthorized

---

src/Skedify.test.js
src/__snapshots__/Skedify.test.js.snap
src/decorators/withResources/createRequest.js
test/testUtils.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4742

feature/SKED-4742: Setup base node service package

---

src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/subjects.js

See JIRA: https://skedify.atlassian.net/browse/SKED-4675

feature/SKED-4675: Configure the outcome list to use for a subject

---

src/Skedify.test.js
src/__snapshots__/Skedify.test.js.snap
src/decorators/withConfig/validate.js
src/decorators/withResources/Resource.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4797

feature/SKED-4797: Allow to override locale on request level basis

---

src/Skedify.test.js
src/SkedifyAPI.js
src/__snapshots__/Skedify.test.js.snap
src/decorators/withDefaults/index.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4821

feature/SKED-4821: Improve performance of timetable slot creation

---

src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/appointmentOutcomes.js
src/resources/appointments.js
src/resources/index.js
src/resources/outcomes.js
src/resources/subjects.js

> See JIRA https://skedify.atlassian.net/browse/SKED-4681

feature/SKED-4681: Register outcomes on appointment completion 

---

README.md
package-lock.json
package.json
src/Skedify.test.js
src/__snapshots__/Skedify.test.js.snap
src/build/Skedify.testing.js
test/mock.js
test/testUtils.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4883

feature/SKED-4883: mockedRequests should not include setup requests

---

src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/subjects.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4979

feature/SKED-4979: Add missing lead_segment_code filter in sdk on subjects resource

---

src/resources/__snapshots__/index.test.js.snap
src/resources/definedAvailability.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4965

feature/SKED-4965: Expand timetable service for on-location appointments

---

src/resources/__snapshots__/index.test.js.snap
src/resources/timetable.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-5059

feature/SKED-5059: Add missing geolocation filter on timetable

---

src/resources/__snapshots__/index.test.js.snap
src/resources/leadSegmentSubjects.js

See JIRA: https://skedify.atlassian.net/browse/SKED-5061

feature/SKED-5061: Filter for lead_segment_subjects with lead_segment_id

---

src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/offices.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4958

feature/SKED-4958: Add multiple meeting type support to the plugin

---

src/resources/__snapshots__/index.test.js.snap
src/resources/appointments.js
src/resources/callbacks.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-5121

feature/SKED-5121: Add ability to fetch single appointment/callback according to uuid

---

src/resources/__snapshots__/index.test.js.snap
src/resources/calendars.js

See JIRA: https://skedify.atlassian.net/browse/SKED-4686

feature/SKED-4686: Add events subresource to calendars

---

src/__snapshots__/Skedify.test.js.snap
src/decorators/withDefaults/index.js
src/decorators/withResources/createRequest.js
test/mock.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-4321

feature/SKED-4321: Defined Availability: improve queries for performance

---

src/resources/__snapshots__/index.test.js.snap
src/resources/contacts.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-5180

feature/SKED-5180: Cannot remove applied week templates

---

src/createIdentityProvider/identityProviders/createGrant.js
src/createIdentityProvider/identityProviders/index.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-5250

feature/SKED-5250: Timetable service returns 404's when internal access fails during deploy of api-primary

---

src/Skedify.test.js
src/createIdentityProvider/identityProviders/createGrant.js
src/createIdentityProvider/identityProviders/index.js
src/decorators/withResources/createRequest.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-5304
Once this is validated / released, the most important application to bump is the web-app.

feature/SKED-5304: Avoid errors in api_integrations

---

src/Skedify.test.js
src/__snapshots__/Skedify.test.js.snap
src/build/Skedify.testing.js
src/decorators/withResources/createRequest.js
test/mock.js
test/testUtils.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-5032

feature/SKED-5032: Support bulk create and delete in the API

---

package-lock.json
package.json
rollup.config.dev.js
rollup.config.prod.js
src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/appointmentOutcomes.js
src/resources/outcomeLists.js
src/resources/outcomes.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-3425

feature/SKED-3425: Allow enterprises to manage their own cancellation reasons

---

src/resources/__snapshots__/index.test.js.snap
src/resources/definedAvailability.js
src/resources/integrations.js
src/resources/offices.js
src/resources/timetable.js
src/resources/unavailability.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-5882

feature/SKED-5882: Add location[geolocation] as filter on GET /offices

---

src/decorators/withResources/createRequest.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-5944

feature/SKED-5944: Plugin not working on IE11

---

src/resources/__snapshots__/index.test.js.snap
src/resources/appointments.js

> See JIRA https://skedify.atlassian.net/browse/SKED-5547

feature/SKED-5547: (U) Introduce paging & only fetch upcoming appointments on team/appointments page

---

src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/users.js

> See JIRA: https://skedify.atlassian.net/browse/SKED-6049

feature/SKED-6049: Admin view on synced calendars of an employee

---

src/resources/__snapshots__/index.test.js.snap
src/resources/definedAvailability.js
src/resources/timetable.js

> See JIRA https://skedify.atlassian.net/browse/SKED-6093

feature/SKED-6093: (U) Allow to pass postal code to timetable

---

README.md
src/decorators/withResources/Resource.js

> See JIRA https://skedify.atlassian.net/browse/SKED-6470

feature/SKED-6470: (U) Fix reassign issues reported by Tryg

---

README.md
src/Skedify.test.js
src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/appointments.js
src/resources/offices.js

> See JIRA https://skedify.atlassian.net/browse/SKED-6179

feature/SKED-6179: Introduce paging on Team > appointments page

---

src/resources/__snapshots__/index.test.js.snap
src/resources/appointments.js

> See JIRA https://skedify.atlassian.net/browse/SKED-6562

feature/SKED-6562: add order_by_start filter on appointments

---

.github/workflows/release.yml

> See JIRA https://skedify.atlassian.net/browse/SKED-5467

feature/SKED-5467: Move SDK from travis to GitHub actions

---

.github/workflows/ci.yml
.github/workflows/release.yml

> See JIRA https://skedify.atlassian.net/browse/SKED-5467

feature/SKED-5467: Move SDK from travis to GitHub actions (add node version to cache key)

---

README.md
package.json
src/Skedify.test.js
src/__snapshots__/Skedify.test.js.snap
src/constants/exported.js
src/decorators/withConfig/validate.js
src/decorators/withResources/Resource.js

> See JIRA https://skedify.atlassian.net/browse/SKED-7259

feature/SKED-7259: Handle token expired redirect

---

src/decorators/withResources/Resource.js

> See JIRA https://skedify.atlassian.net/browse/SKED-6208

feature/SKED-6208: email service (fix breaking change introduced in 4.47.0 (SKED-7259))

---

index.html
src/resources/__snapshots__/index.test.js.snap
src/resources/employees.js

> See JIRA https://skedify.atlassian.net/browse/SKED-7118
⚠️ do not merge, wait for api-primary part ⚠️

Update SDK for favorite contacts

---

src/__snapshots__/Skedify.test.js.snap
src/resources/__snapshots__/index.test.js.snap
src/resources/appointments.js

> https://skedify.atlassian.net/browse/SKED-7702

feature/SKED-7702 : External calendar events content is not working correctly?

---

types/appointment.d.ts
types/contactOffices.d.ts
types/customer.d.ts
types/index.d.ts

> See JIRA https://skedify.atlassian.net/browse/SKED-7749

feature/SKED-7749: added appointments

---

.github/workflows/release-candidate.yml
README.md
index.html
src/Skedify.test.js
src/SkedifyAPI.js
src/__snapshots__/Skedify.test.js.snap
src/createIdentityProvider/identityProviders/createGrant.js
src/decorators/withExposedAuthorization.js
test/mock.js
test/testUtils.js

> See JIRA https://skedify.atlassian.net/browse/SKED-7961

feature/SKED-7961: Expose Authentication header on the SDK instance
